# Generated by Django 5.0.1 on 2025-03-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_apptask_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='apptask',
            name='app_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
