# Generated by Django 5.0.1 on 2025-03-19 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_apptask_app_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='app_task',
        ),
        migrations.AddField(
            model_name='submission',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.apptask'),
        ),
    ]
